server:
  port: 18002

eureka:
  instance:
    hostname: "eurakeServer18002"
  client:
    service-url:
      defaultZone: "http://eurekaServer18001:18001/eureka/,http://eurekaServer18000:18000/eureka/"
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false