server:
  port: 18000

eureka:
  instance:
    hostname: "eurakeServer18000"
  client:
    service-url:
      defaultZone: "http://eurekaServer18001:18001/eureka/,http://eurekaServer18002:18002/eureka/"
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false



