server:
  port: 12000
spring:
  application:
    name: "gateway-service"
  cloud:
    gateway:
      routes:
        - id: consumerService
          uri: lb://consumer-service
          predicates:
            - Path=/cart/getCartById/**
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                fallbackUri: "forward:/fallback"
        - id: providerService
          uri: lb://provider-service
          predicates:
            - Path=/user/getUserById/**

eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://localhost:18000/eureka/"
